locale: 'de'

backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: 'pages'
    label: 'Seiten'
    folder: 'content'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Inhalt', name: 'body', widget: 'markdown' }
