name: Build and Test

on:
  push:
    branches:
      - KillYourMaster
  pull_request:
  repository_dispatch:
    types: deploy

env:
  GATSBY_TELEMETRY_DISABLED: 1
  NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Build & test the application
        run: |
          npm install
          npm test
          npm run build

      - name: Deploy the application
        if: github.ref == 'refs/heads/KillYourMaster'
        run: npm run deploy
